require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/alternativas", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Alternativa. As you add validations to Alternativa, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Alternativa.create! valid_attributes
      get alternativas_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      alternativa = Alternativa.create! valid_attributes
      get alternativa_url(alternativa)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_alternativa_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      alternativa = Alternativa.create! valid_attributes
      get edit_alternativa_url(alternativa)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Alternativa" do
        expect {
          post alternativas_url, params: { alternativa: valid_attributes }
        }.to change(Alternativa, :count).by(1)
      end

      it "redirects to the created alternativa" do
        post alternativas_url, params: { alternativa: valid_attributes }
        expect(response).to redirect_to(alternativa_url(Alternativa.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Alternativa" do
        expect {
          post alternativas_url, params: { alternativa: invalid_attributes }
        }.to change(Alternativa, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post alternativas_url, params: { alternativa: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested alternativa" do
        alternativa = Alternativa.create! valid_attributes
        patch alternativa_url(alternativa), params: { alternativa: new_attributes }
        alternativa.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the alternativa" do
        alternativa = Alternativa.create! valid_attributes
        patch alternativa_url(alternativa), params: { alternativa: new_attributes }
        alternativa.reload
        expect(response).to redirect_to(alternativa_url(alternativa))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        alternativa = Alternativa.create! valid_attributes
        patch alternativa_url(alternativa), params: { alternativa: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested alternativa" do
      alternativa = Alternativa.create! valid_attributes
      expect {
        delete alternativa_url(alternativa)
      }.to change(Alternativa, :count).by(-1)
    end

    it "redirects to the alternativas list" do
      alternativa = Alternativa.create! valid_attributes
      delete alternativa_url(alternativa)
      expect(response).to redirect_to(alternativas_url)
    end
  end
end
