# This is a basic workflow to help you get started with Actions

name: Trabalho_Eng_Sistemas_Inf

on: [push, pull_request]

jobs:
  
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1

      - name: Install dependencies
        run: bundle install
      
      - name: Unit Tests
        run: bundler exec rake

      - name: User Stories Test
        run: echo Hello, world!
  
  prod: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run a one-line script
        run: echo Deploy de prod
