# This is a basic workflow to help you get started with Actions

name: Trabalho_Eng_Sistemas_Inf

on: [push, pull_request]

jobs:
  
  test:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: bundle install
      
      - name: Unit Tests
        run: bundler exec rake

      - name: User Stories Test
        run: bundler exec cucumber
        
 
  coverals:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
  
  prod: 
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Run a one-line script
        run: echo Deploy de prod
