# This is a basic workflow to help you get started with Actions

name: Trabalho_Eng_Sistemas_Inf
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
  dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run a one-line script
        run: echo Deploy de Dev
  prod: 
    runs-on: ubuntu-latest
    needs: dev
    steps:
      - name: Run a one-line script
        run: echo Deploy de prod
